### ISSUE TITLE
Just a question (yeah im bored)

### ISSUE THREAD

**Issue by Exorcism0666** [carcaschoi/wiihe#1]
Howdy! I just saw your video which came out 2 hours ago and I wanted to know if it was necessary to put the same parameters at this precise moment 

![image](https://user-images.githubusercontent.com/46537034/140540212-fb340fa8-7fb5-4b15-b898-119a9355add1.png)

(because I have a European wii and I do not know if I should put everything like you ie "Japan" after "Taiwan" etc ... or simply change something without modifying too much)

**Comment by carcaschoi** [comment]
You want to install Chinese system patches on your wii？

**Comment by Exorcism0666** [comment]
Yep, even if I don't understand anything, it's impressive and amazing 😂

**Comment by Exorcism0666** [comment]
Howdy! just to warn you that I managed to install the Chinese version as you show in the video, but I didn't need to use "Anyregion changer" because as soon as I installed the .wad files, I wanted to know what it would do if I left the homebrew channel, in the end everything works fine for European Wii I guess (PAL)

carcaschoi: Well……I think you cannot enter the setting screen now.

Exorcism: Yup, The problem is that, as soon as I want to start the homebrew "Anyregion changer" my controller automatically disconnects and no way to navigate in the menu
